### ISSUE TITLE
cli hanging on deploy command

### ISSUE THREAD

**Issue by aafrey** [alexellis/faas-cli#16]
Running through the demo commands in the README. Install seemed to go fine as did build the sample functions with `faas-cli -action build -f ./samples.yml`

When deploy though, it seems to hang.
`faas-cli -action deploy -f ./samples.yml`
...hangs with `Deploying: url_ping.`

This is on x86 architecture and Docker 17.06.0-ce.

**Comment by alexellis** [comment]
What version of the `faas-cli` did you have?

**Comment by alexellis** [comment]
I have 0.4 - just installed 17.06.0-ce on my Mac:

```
$ faas-cli -version
Git Commit: 340e34cfacf3376cae1cdab269e301c74ebc4752
```

```
$ faas-cli -action deploy -f ./samples.yml
Deploying: url_ping.
No existing service to remove
200 OK
URL: http://localhost:8080/function/url_ping

Deploying: get_captains.
No existing service to remove
200 OK
URL: http://localhost:8080/function/get_captains

Deploying: node_info.
No existing service to remove
200 OK
URL: http://localhost:8080/function/node_info
```

What platform / OS are you testing on?

**Comment by aafrey** [comment]
@alexellis 
```
faas-cli --version
Git Commit: 340e34cfacf3376cae1cdab269e301c74ebc4752

uname -ipmo
x86_64 x86_64 x86_64 GNU/Linux
```
this was on a scaleway server, but I'm thinking it was some kind of network issue. on my home PC this afternoon I had no issues :)

do you want me to close this? I can keep it open and do some further digging if it would be helpful.

**Comment by alexellis** [comment]
I'll close this issue, but if you can do more digging that would be appreciated. Re-open if needed.
