### ISSUE TITLE
-action build should copy sub-folders into template

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas-cli#18]
When building a function with a node template for instance any additional sub-folders are not copied into the final image - just flat files at the root.

This should be a change in the build step in https://github.com/alexellis/faas-cli/blob/master/app.go#L293

**Comment by rgee0** [comment]
Possibly employ recursion in the copy files function to traverse the directory tree.

Happy to have a look at this.

**Comment by alexellis** [comment]
Cheers @rgee0 - awesome to get this contribution.

**Comment by alexellis** [comment]
Fixed in #21
