### ISSUE TITLE
Bump Golang version to 1.8.x

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas-cli#40]
## Expected Behaviour

We need to start moving the FaaS projects to 1.8.x. The CLI has the least complex dependency-set so let's start here.

## Current Behaviour

We're using 1.7.x for x86 and ARM.

## Possible Solution

* Update Dockerfiles to best available 1.8.x version
* Run unit tests
* Do integration testing with Docker Swarm and K8s

**Comment by johnmccabe** [comment]
Contentious, but should we skip 1.8 and bump to 1.9 - its due "real soon now" (TM), and we could use the rc build images in the meantime

**Comment by alexellis** [comment]
I think 1.8 may be better interim step since that's what the Docker client/API (main dependency) is building against. The K8s work should be on 1.8 but we're somehow getting away with 1.7.

**Comment by alexellis** [comment]
Suggesting 1.8.3.

**Comment by alexellis** [comment]
Fixed in #51
