### ISSUE TITLE
Enhancement - CLI should support function deletion

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/faas-cli#42]
## Issue

It is not possible to delete functions via the FaaS CLI.

### Proposed fix

Extend `faas-cli` with the ability to delete a specified function.

Suggest we do do after #17 has been implemented and do so via the `faas-cli delete <fn>` verb based approach.

**Comment by alexellis** [comment]
Fixed in #41 - all commands will use a verb-based approach with the new CLI, right?

**Comment by johnmccabe** [comment]
correct
