### ISSUE TITLE
Docs using ./faas-cli instead of faas-cli

### ISSUE THREAD

**Issue by binoy14** [alexellis/faas-cli#48]
Simple documentation fix in Readme.md to change it from ./faas-cli to faas-cli so it doesn't confuse beginners.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Using faas-cli via PATH, rather than dev version is a good idea 👍 Done..
