### ISSUE TITLE
on faas-cli -action deploy: dial tcp 127.0.0.1:8080: getsockopt: connection refused

### ISSUE THREAD

**Issue by ems5311** [alexellis/faas-cli#49]
When attempting to deploy a function with `faas-cli -action deploy -f ./urlping.yaml` I get the following error message:

```
~/github/faas-cli$ sudo ./faas-cli -action deploy -f ./urlping.yaml 
Deploying: url_ping.
Error removing existing function: Delete http://localhost:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused, gateway=http://localhost:8080, functionName=url_ping
Is FaaS deployed? Do you need to specify the -gateway flag?
Post http://localhost:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused

```

The file, urlping.yaml, is as described in the README.md example file.

This happens with both the faas-cli downloaded from https://cli.openfaas.com, or one which I have compiled from this repo.

## Expected Behaviour

Deploys function

## Current Behaviour

Produces output pasted above

## Steps to Reproduce (for bugs)

1. Follow readme until `faas-cli -action deploy -f ./urlping.yaml`
2. run `faas-cli -action deploy -f ./urlping.yaml`
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.1-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
no
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 16.04
* Link to your project or a code example to reproduce issue:

**Comment by ems5311** [comment]
Update - This error is due to a docker stack not being deployed on localhost:8080, or another docker service already occupying that address and port. I had a service running on localhost:8080, so I removed it, and ran the ./deploy_stack.sh script in the faas/ repository, which set up a single node docker swarm cluster on my local machine, enabling me to deploy a function with faas-cli.

**Comment by alexellis** [comment]
Good point .. glad you could figure it out. https://github.com/alexellis/faas/commit/e40730f7405dd54e3079fac20e2d0d01a80fc754
