### ISSUE TITLE
Update fwatchdog to 0.6.1 and update command help message

### ISSUE THREAD

**Issue by itscaro** [alexellis/faas-cli#56]
## Expected Behaviour
Update all Dockerfiles in samples directory to get the latest version of fwatchdog, 0.6.1
Update help message for "action" option to include "push" and "delete" keywords

**Comment by alexellis** [comment]
I'm not sure what this issue is for? Did you want to fill in the template please?

**Comment by alexellis** [comment]
Thanks for filling in the template.. 👍

**Comment by alexellis** [comment]
Merged changes in #57
