### ISSUE TITLE
Proposal - automate adding cli binaries to Github release on tag

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/faas-cli#67]
## Expected Behaviour
Tagging a release should automatically upload the built cli binaries to the Github release from Travis.

**Comment by johnmccabe** [comment]
I'll push up a PR showing how to do this

**Comment by johnmccabe** [comment]
Derek add label: skill/beginner

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add a label that @johnmccabe is killing it. 👍

**Comment by alexellis** [comment]
Merged via travis changes.
