### ISSUE TITLE
Proposal: Add init/new/create commands to the CLI

### ISSUE THREAD

**Issue by alias1** [alexellis/faas-cli#70]
It would be nice if all of the required 'knowledge' for creating a new function/etc was built into the command line, with something akin to `faas-cli init funcName`

## Expected Behaviour

Be able to create a new function/etc with ease from the command line

## Current Behaviour

Need to read through a lot of different places to understand how to create a new function.

## Possible Solution

Add init/new/create commands to the CLI that walk a new user through creating a new function, or setting up a stack. Ideally this would allow parameters to be passed directly on the command line, and if they are missing, to 'guide' the user through the process. eg

```
faas-cli new function

Name []: foo-func
Language [python]: golang 
etc
```

The available 'templates' would be those currently usable, with optional support for pulling remote repos (such as a 3rd party template on github)

Additionally, it would be good to be able to setup a FaaS gateway stack as easy as we can do `docker swarm init`.

## Steps to Reproduce (for bugs)

N/A

## Context

When starting a new OpenFaaS based project, there are numerous steps to getting started, that currently seem to require reading a bunch of README's, samples, and blog posts. Minimising this to as few 'built in' steps would ease the onboarding requirement for new users.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): 17.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* Link to your project or a code example to reproduce issue: N/A

**Comment by alexellis** [comment]
Hey @alias1 all good ideas. If you'd like to submit a lot of feedback how about joining us on Slack to chat synchronously?

**Comment by alexellis** [comment]
> Need to read through a lot of different places to understand how to create a new function.

Did you try the samples in the CLI?

**Comment by alias1** [comment]
Emailed RE: Slack. As I probably don't have the capacity to implement, I thought putting them somewhere public people can see/comment/take on would be useful.

Have had a read through them, and started to work from them for my own project. This (and the other) comments are more calling out things that would improve the UX/etc as I see them, as I find the best time to notice these sorts of things is when you first start using a project and have no idea what you're doing with it ;p (aka, me now :p)

**Comment by alias1** [comment]
Looks like this landed in https://github.com/alexellis/faas-cli/commit/e0131833325dc900f9f375a240ddb708e657503a If so, this can be closed.
