### ISSUE TITLE
Proposal: Add 'list' command to the CLI

### ISSUE THREAD

**Issue by alias1** [alexellis/faas-cli#73]
## Expected Behaviour

It would be nice to be able to list the functions on the current gateway from the CLI. This would improve the functionality of the CLI, and make discoverability/updates easier.

I am thinking in a similar vein to how apex does things:
* http://apex.run/#listing-functions

**Comment by johnmccabe** [comment]
I'd noticed @itscaro had a [local branch](https://github.com/itscaro/faas-cli/tree/add-command-to-list-registered-function) where he was working on something like this.

**Comment by alias1** [comment]
Looks like this landed in https://github.com/alexellis/faas-cli/commit/0bdfbcb26bc56480e9bde5a0728ce9a0ef7bdcce If so, this can be closed now.
