### ISSUE TITLE
Proposal: Add 'invoke' command to the CLI

### ISSUE THREAD

**Issue by alias1** [alexellis/faas-cli#74]
## Expected Behaviour

It would be nice to be able to invoke functions on the current gateway from the CLI. This would improve the functionality of the CLI.

I am thinking in a similar vein to how apex does things:
* http://apex.run/#invoking-functions

**Comment by alexellis** [comment]
Are you also aware that there is a UI built-in for testing functions?

**Comment by alias1** [comment]
By that do you mean the WebUI on `:8080`? If so, I am, and it is nice, but I see a lot of power in being able to use this like an extension of 'local' CLI applications, and build it into my workflow that way.

Obviously I can do it with curl/through the UI/wrap my own thing to do it, but in the vein of improving the 'all in one' functionality this CLI provides, it would be a nice addition.

**Comment by alias1** [comment]
Looks like this landed in https://github.com/alexellis/faas-cli/commit/0bdfbcb26bc56480e9bde5a0728ce9a0ef7bdcce If so, this can be closed now.

**Comment by alias1** [comment]
Looks like there are a few hangovers from the file it was copied from (handler, image, language):
* https://github.com/alexellis/faas-cli/blob/master/commands/invoke.go#L26-L28

**Comment by alexellis** [comment]
Thanks, we'll clear them up in the next binary
