### ISSUE TITLE
build action template download/extraction fails on Windows

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/faas-cli#94]
## Expected Behaviour
Build should "just work"

## Current Behaviour

Fails with:
```
C:\Users\alex\Desktop\faas\sample-functions\ipconfig>.\faas-cli.exe build -f stack.yml
2017/09/12 05:57:49 No templates found in current directory.
2017/09/12 05:57:49 HTTP GET https://github.com/alexellis/faas-cli/archive/master.zip
2017/09/12 05:57:51 Writing 200Kb to master.zip
2017/09/12 05:57:51 Attempting to expand templates from master.zip
Found template/.
Writing 0 bytes to template/.
2017/09/12 05:57:51 Unable to download templates from Github.
2017/09/12 05:57:51 Could not pull templates for OpenFaaS. open template/: is a directory
```
Note this has been around for a while, reproduced on current release and old `0.4.8`

## Steps to Reproduce (for bugs)

1. Build a sample function on windows

## Context

User experience on Windows is compromised

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 17.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

**Comment by johnmccabe** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
Derek add label: windows

**Comment by alexellis** [comment]
Fixed in: https://github.com/alexellis/faas-cli/commit/9bf8cee146c2ccddfb12d91db7e049e8dc763dc9
