### ISSUE TITLE
Proposal: Do a gofmt verification before build

### ISSUE THREAD

**Issue by itscaro** [alexellis/faas-cli#95]
## Expected Behaviour
If there is a file which need to be reformatted, the docker build is interrupted.
 
## Current Behaviour
There is no verification.

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by itscaro** [comment]
Please close this issue as the PR is merged. I forgot to put in commit message token to close issue automatically

**Comment by alexellis** [comment]
Merged 👍
